
- hosts: tag_Name_autoscaling_group_name
  become: true

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        # Add other required packages

    - name: Copy application files
      copy:
        src: /path/to/app
        dest: /var/www/html/
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
